abstract: Simple SVK object loader
author: Kang-min Liu <gugod@gugod.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: SVK-Simple
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Field: 0.12
  SVK: 0.30
version: 0.03
